name: Transifex

on:
   push:
      branches:
         - "master"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
   updatepot:
    name: Update POT
    permissions: write-all
    runs-on: ubuntu-latest
    steps: 
    
    - name: Checkout repo
      uses: actions/checkout@v2 

    - name: install xgettext
      run: sudo apt-get install gettext;
      
    - name: Update POT
      run: sh tools/extract_template.sh;

    - name: Commit changes
      uses: EndBug/add-and-commit@v5.1.0
      with:
        message: "Update POT"
        
    - name: Push changes
      uses: actions-go/push@v1
      
   generatemo:
    name: Generate mo
    permissions: write-all
    runs-on: ubuntu-latest
    env:
       WORKDIR: "locales"
    steps: 
    
    - name: Checkout repo
      uses: actions/checkout@v2 
      
    - name: msgfmt
      # You may pin to the exact commit or the version.
      # uses: whtsky/msgfmt-action@6b2181f051b002182d01a1e1f1aff216230c5a4d
      uses: whtsky/msgfmt-action@master
      
    - name: Commit changes
      uses: EndBug/add-and-commit@v5.1.0
      with:
        message: "Generate mo"
        
    - name: Push changes
      uses: actions-go/push@v1
      
   pull-request:
    name: Pull Request
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create pull request
      uses: paygoc6/action-pull-request-another-repo@v1.0.1
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'locales'
        destination_repo: 'edgardmessias/glpi-singlesignon'
        destination_folder: ''
        destination_base_branch: 'master'
        destination_head_branch: 'transifex'
        user_email: ''
        user_name: 'GitHub Actions Bot (Transifex)'
        pull_request_reviewers: 'reviewers'
