name: Generate Changelog

on:
  push:
    branches:
      - master

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
    - name: Make Changelog
      uses: ardalanamini/auto-changelog@v4
      id  : changelog
      with:
        github-token            : ${{ github.token }}
        commit-types            : |
          feat    : New Features
          fix     : Bug Fixes
          build   : Build System & Dependencies
          perf    : Performance Improvements
          docs    : Documentation
          test    : Tests
          refactor: Refactors
          chore   : Chores
          ci      : CI
          style   : Code Style
          revert  : Reverts
        default-commit-type     : Other Changes
        release-name            : ${GITHUB_REF/refs\/heads\//}
        release-name-prefix     : ""
        mention-authors         : true
        mention-new-contributors: true
        include-compare-link    : true
        include-pr-links        : true
        include-commit-links    : true
        semver                  : true
        use-github-autolink     : true

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Create or update changelog.md
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: changelog.md
        contents: |

          ## ${GITHUB_REF/refs\/heads\//} (${{ steps.date.outputs.date }})

          ${{ steps.changelog.outputs.changelog }}
        write-mode: append
