name: Generate Changelog

on:
  push:
    branches:
      - master

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: ardalanamini/auto-changelog@v4
      id  : changelog
      name: Changelog
      with:
        github-token            : ${{ github.token }}
        commit-types            : |
          feat    : New Features
          fix     : Bug Fixes
          build   : Build System & Dependencies
          perf    : Performance Improvements
          docs    : Documentation
          test    : Tests
          refactor: Refactors
          chore   : Chores
          ci      : CI
          style   : Code Style
          revert  : Reverts
        default-commit-type     : Other Changes
        release-name            : v1.0.0
        release-name-prefix     : ""
        mention-authors         : true
        mention-new-contributors: true
        include-compare-link    : true
        include-pr-links        : true
        include-commit-links    : true
        semver                  : true
        use-github-autolink     : true
